version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt

jobs:
    pre_build:
      - pip install myst-parser

sphinx:
  configuration: docs/conf.py
